on:
  workflow_call:
    inputs:
      definitionsRootFolder:
        required: true
        type: string
      pacEnvironment:
        required: true
        type: string
      planFolder:
        required: true
        type: string
      epac_pinned_version:
        required: true
        type: string
      az_pinned_version:
        required: true
        type: string
      graph_pinned_version:
        required: true
        type: string
      resources_pinned_version:
        required: true
        type: string

jobs:
  epac-deployPolicy:
    name: Deploy Policy Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    environment:
      name: ${{ inputs.pacEnvironment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Deployment Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: deploymentPlan
        continue-on-error: false

      - name: Copy Artifact to Output Folder
        run: |
          mkdir -p "${{ inputs.planFolder }}/plans-${{ inputs.pacEnvironment }}"
          cp -r "plans-${{ inputs.pacEnvironment }}/." "${{ inputs.planFolder }}/plans-${{ inputs.pacEnvironment }}/"
        shell: bash

      - name: Authenticate with Azure using OIDC
        uses: Azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          enable-AzPSSession: true

      - name: Install Required PowerShell Modules
        shell: pwsh
        run: |
          Write-Output "Installing required modules..."
          Install-Module -Name Az -RequiredVersion ${{ inputs.az_pinned_version }} -Force -AllowClobber
          Install-Module -Name Az.ResourceGraph -RequiredVersion ${{ inputs.graph_pinned_version }} -Force -AllowClobber
          Install-Module -Name Az.Resources -RequiredVersion ${{ inputs.resources_pinned_version }} -Force -AllowClobber

          if (($null -eq "${{ inputs.epac_pinned_version }}" -or "${{ inputs.epac_pinned_version }}" -eq 'latest')) {
            Write-Output "No pinned version specified for EPAC. Installing the latest version."
            Install-Module -Name EnterprisePolicyAsCode -AllowClobber -Force
          } else {
            Write-Output "Installing EPAC version: ${{ inputs.epac_pinned_version }}"
            Install-Module -Name EnterprisePolicyAsCode -RequiredVersion ${{ inputs.epac_pinned_version }} -AllowClobber -Force
          }

      - name: Deploy Policy Plan
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Deploy-PolicyPlan `
              -definitionsRootFolder ${{ inputs.definitionsRootFolder }} `
              -inputFolder ${{ inputs.planFolder }} `
              -pacEnvironment ${{ inputs.pacEnvironment }}
          azPSVersion: "latest"
